steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy:$COMMIT_SHA'
      - .
    id: Build Container Image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy:$COMMIT_SHA'
    id: Push Image to Container Registry
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - db-updater
      - '--image'
      - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--env-vars-file'
      - 'db-updater-dev.yaml'
      - '--platform'
      - managed
    id: Deploy Container on Google Cloud Run
images:
  - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy:$COMMIT_SHA'